dataset:
  time:
    path: mutation_results/time/
    initial: 0.7807
    flakerates:
      0.0: 10
      0.01: 2
      0.02: 2
      0.03: 2
      0.04: 2
      0.05: 2
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  lang:
    path: mutation_results/lang/
    initial: 0.8558
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  charts:
    path: mutation_results/charts/
    initial: 0.3173
    flakerates:
      0.0: 2
      0.01: 2
      0.02: 2
      0.03: 2
      0.04: 2
      0.05: 2
      0.06: 2
      0.07: 2
      0.08: 2
      0.09: 2
      0.1: 7
      0.2: 10
      0.3: 2
      0.4: 2
      0.5: 2
  math:
    path: mutation_results/math/
    initial: 0.7878
    flakerates:
      0.0: 2
      0.02: 1
      0.03: 2
      0.04: 2
      0.06: 2
      0.08: 2
      0.1: 9
      0.2: 5
      0.3: 13
      0.4: 2
      0.5: 2
