project:

  time-19:
    path: prapr_results/time/19
    n_patches: 3865
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  lang-6:
    path: prapr_results/lang/6
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  math-5:
    path: prapr_results/math/5
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  math-34:
    path: prapr_results/math/34
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10

  math-85:
    path: prapr_results/math/85
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10


  chart-1:
    path: prapr_results/chart/1
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  chart-11:
    path: prapr_results/chart/11
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  chart-12:
    path: prapr_results/chart/12
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  chart-20:
    path: prapr_results/chart/20
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  chart-24:
    path: prapr_results/chart/24
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  mock-29:
    path: prapr_results/mock/29
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  mock-38:
    path: prapr_results/mock/38
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10

### above 30
  chart-26:
    path: prapr_results/chart/26
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  time-11:
    path: prapr_results/time/11
    n_patches: 2952
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 11
      0.3: 10
      0.4: 10
      0.5: 10
  math-50:
    path: prapr_results/math/50
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10
  math-82:
    path: prapr_results/math/82
    n_patches: 206
    flakerates:
      0.0: 10
      0.1: 10
      0.2: 10
      0.3: 10
      0.4: 10
      0.5: 10